"""Publishes an OCI container image to a Docker registry.

Composes a base image + the binary's runfiles tar (+ optional extra
layers) into an oci_image, then wraps oci_push in a generated shell
script that resolves the registry URL/repo from publish_config,
authenticates against the registry via docker_login_helper, and pushes
the image at `<PUBLISH_DOCKER_URL>/<PUBLISH_DOCKER_REPO>/<artifact_id>:<PUBLISH_VERSION>`.

For Java fat-JAR images, point binary_target at the canonical's
_deploy.jar implicit output (e.g., ":java_app_deploy.jar"). For native
binaries (Go/Rust/C++) and Python, point at the binary itself
(e.g., ":foo") — tar.bzl includes the runfiles tree automatically when
srcs is an executable target.
"""

load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_push")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("@tar.bzl", "mutate", "tar")

# Container images are deployed to linux/amd64; the base image alias
# generated by oci.pull only enumerates linux variants. Forcing this
# platform during oci_image analysis lets the alias resolve on any host
# (notably darwin CI runners) and keeps the produced image consistent
# with the deployment target.
_IMAGE_TARGET_PLATFORM = "//tools/cpp/toolchains:x86_64_linux_platform"

# Placeholder expanded at macro evaluation with the elements of
# runtime_args. Allowed at most once per entrypoint.
_RUNTIME_ARGS_PLACEHOLDER = "{runtime_args}"

def _validate_no_single_quotes(value, name):
    if "'" in value:
        fail("{} must not contain single quotes (got: {})".format(name, value))

def _validate_app_prefix(app_prefix):
    if app_prefix.startswith("/"):
        fail("app_prefix must not have a leading slash; got: '" + app_prefix + "'")
    if app_prefix.endswith("/"):
        fail("app_prefix must not have a trailing slash; got: '" + app_prefix + "'")
    if ".." in app_prefix.split("/"):
        fail("app_prefix must not contain '..' segments; got: '" + app_prefix + "'")

def _expand_entrypoint(entrypoint, runtime_args):
    placeholder = _RUNTIME_ARGS_PLACEHOLDER
    placeholder_count = 0
    expanded = []
    for token in entrypoint:
        if token == placeholder:
            placeholder_count += 1
            expanded = expanded + list(runtime_args)
        else:
            expanded.append(token)
    if placeholder_count > 1:
        fail("entrypoint may contain at most one '{runtime_args}' placeholder; got {}".format(placeholder_count))
    if runtime_args and placeholder_count == 0:
        fail("runtime_args supplied but entrypoint contains no '{runtime_args}' placeholder")
    return expanded

def _package_dir(app_prefix):
    """Construct the package_dir for tar.bzl's mutate(package_dir=...).

    tar.bzl expects a relative path (no leading slash); the empty prefix
    case lays files at the tar root.
    """
    return app_prefix

def _wrapper_script_content(name, artifact_id, package):
    """Build the wrapper script that resolves config, authenticates, pushes.

    The script is a write_file output, fed to a sh_binary that depends
    on the inner oci_push as data. At `bazel run` time it sources
    publish_config.sh (.bazelrc-derived defaults), validates the runtime
    env (PUBLISH_DOCKER_URL, PUBLISH_DOCKER_REPO with generic_repo
    fallback, PUBLISH_VERSION), invokes docker_login_helper to populate
    ~/.docker/config.json, then execs the oci_push launcher with
    --repository / --tag derived from the resolved config.
    """

    # oci_push declares its launcher as "push_<target>.sh". Our private
    # push target is "_<name>_push", so the launcher lands at
    # "push__<name>_push.sh" in the inner target's package directory of
    # runfiles.
    push_executable = "push__" + name + "_push.sh"
    push_runfiles_path = "_main/" + package + "/" + push_executable

    return [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "RUNFILES=\"${BASH_SOURCE[0]}.runfiles\"",
        "if [[ ! -d \"${RUNFILES}\" ]]; then",
        "    RUNFILES=\"${0}.runfiles\"",
        "fi",
        "",
        "source \"${RUNFILES}/_main/tools/publish/publish_config.sh\"",
        "",
        "PUBLISH_DOCKER_URL=\"${PUBLISH_DOCKER_URL:-${PUBLISH_DOCKER_URL_DEFAULT:-}}\"",
        "if [[ -z \"${PUBLISH_DOCKER_URL}\" ]]; then",
        "    echo 'ERROR: No image registry URL configured.' >&2",
        "    echo 'Set PUBLISH_DOCKER_URL env var or configure --//tools/publish:docker_url.' >&2",
        "    exit 1",
        "fi",
        "",
        "PUBLISH_DOCKER_REPO=\"${PUBLISH_DOCKER_REPO:-${PUBLISH_DOCKER_REPO_DEFAULT:-}}\"",
        "if [[ -z \"${PUBLISH_DOCKER_REPO}\" ]]; then",
        "    PUBLISH_DOCKER_REPO=\"${PUBLISH_GENERIC_REPO:-${PUBLISH_GENERIC_REPO_DEFAULT:-}}\"",
        "fi",
        "if [[ -z \"${PUBLISH_DOCKER_REPO}\" ]]; then",
        "    echo 'ERROR: No image repository configured.' >&2",
        "    echo 'Configure --//tools/publish:docker_repo (or :generic_repo as fallback).' >&2",
        "    exit 1",
        "fi",
        "",
        "if [[ -z \"${PUBLISH_VERSION:-}\" ]]; then",
        "    echo 'ERROR: PUBLISH_VERSION is required.' >&2",
        "    echo 'Use mint: bazel run //tools/publish:mint -- --mode dev' >&2",
        "    echo 'Or set directly: PUBLISH_VERSION=1.0.0 bazel run --config=publish ...' >&2",
        "    exit 1",
        "fi",
        "",
        # OCI registries take bare host[:port][/path] — strip scheme and
        # trailing slash so users may set PUBLISH_DOCKER_URL with or
        # without https://.
        "DOCKER_URL_BARE=\"${PUBLISH_DOCKER_URL#http://}\"",
        "DOCKER_URL_BARE=\"${DOCKER_URL_BARE#https://}\"",
        "DOCKER_URL_BARE=\"${DOCKER_URL_BARE%/}\"",
        "REGISTRY_HOST=\"${DOCKER_URL_BARE%%/*}\"",
        "REPOSITORY=\"${DOCKER_URL_BARE}/${PUBLISH_DOCKER_REPO}/" + artifact_id + "\"",
        "",
        # crane push (the oci_push backend) has no --dry-run flag, so we
        # short-circuit at our layer and skip auth + push. The mint
        # orchestrator captures stderr to surface resolved coordinates.
        "for arg in \"$@\"; do",
        "    if [[ \"${arg}\" == '--dry-run' ]]; then",
        "        echo \"DRY RUN: would push ${REPOSITORY}:${PUBLISH_VERSION}\" >&2",
        "        exit 0",
        "    fi",
        "done",
        "",
        "\"${RUNFILES}/_main/tools/publish/docker_login_helper\" --registry=\"${REGISTRY_HOST}\"",
        "",
        "echo \"Pushing ${REPOSITORY}:${PUBLISH_VERSION}\" >&2",
        "exec \"${RUNFILES}/" + push_runfiles_path + "\" \\",
        "    --repository=\"${REPOSITORY}\" \\",
        "    --tag=\"${PUBLISH_VERSION}\" \\",
        "    \"$@\"",
    ]

def image_publish(
        name,
        binary_target,
        base,
        artifact_id,
        entrypoint,
        runtime_args = [],
        cmd = [],
        app_prefix = "app",
        strip_prefix = "",
        extra_layers = [],
        visibility = None):
    """Composes and pushes an OCI image with binary_target layered on top of base.

    Builds an oci_image from base + the binary's runfiles tar (+ any
    extra_layers) and emits a runnable :<name> sh_binary that resolves
    the registry coordinate from publish_config, authenticates via
    docker_login_helper, and pushes the image.

    Args:
        name: Target name (conventionally "publish_image"). Becomes a
            sh_binary; intermediate targets are named "_<name>_*" and
            kept private.
        binary_target: Label of the binary to package. For java_binary,
            point at ":<canonical>_deploy.jar"; for other kinds, ":<canonical>".
        base: Base image label (e.g., "@gcr_io_distroless_java17").
        artifact_id: Image name in the registry (e.g., "java-app"). Forms
            the last segment of the resolved OCI coordinate.
        entrypoint: Command list for the image. May contain one
            "{runtime_args}" placeholder which is expanded to runtime_args.
        runtime_args: List of strings spliced into the {runtime_args}
            slot. Default empty (slot collapses).
        cmd: Default args appended at container runtime (Docker CMD);
            user-overridable at `docker run` time.
        app_prefix: In-image filesystem prefix where binary lands.
            Default "app". Empty string allowed; leading/trailing slashes
            and ".." segments rejected.
        strip_prefix: Path prefix to strip from binary_target's source-tree
            location before placing it under app_prefix. tar.bzl preserves
            workspace-relative paths by default, so without strip_prefix a
            go_binary at //modules/foo:bar lands at /<app_prefix>/modules/foo/bar_/bar.
            Per-kind values are emitted by gazelle; hand-written calls
            typically pass package_name() (or package_name() + "/<name>_"
            for go_binary/rust_binary, which add an internal subdir).
        extra_layers: Additional tarballs layered on top of the app tar.
        visibility: Bazel visibility for the public sh_binary.
    """

    _validate_no_single_quotes(artifact_id, "artifact_id")
    _validate_app_prefix(app_prefix)
    expanded_entrypoint = _expand_entrypoint(entrypoint, runtime_args)

    # tar.bzl includes runfiles automatically when srcs is an executable.
    # strip_prefix removes the source-tree path; package_dir then anchors
    # the result under the configured app_prefix.
    app_layer = "_" + name + "_app_layer"
    tar(
        name = app_layer,
        srcs = [binary_target],
        mutate = mutate(
            package_dir = _package_dir(app_prefix),
            strip_prefix = strip_prefix,
        ),
        visibility = ["//visibility:private"],
    )

    # The base alias generated by oci.pull only registers linux/amd64; on
    # any other host config its select() has no matching arm and analysis
    # fails. The linux-only constraint here makes `bazel build //...:_<name>_image`
    # at host config get skipped on darwin — but is not sufficient on its
    # own, because the platform_transition_filegroup below reaches this
    # target under a transitioned linux config where the constraint is
    # satisfied. The matching constraint on the wrapper handles that path.
    image = "_" + name + "_image"
    oci_image(
        name = image,
        base = base,
        tars = [":" + app_layer] + extra_layers,
        entrypoint = expanded_entrypoint,
        cmd = cmd,
        target_compatible_with = ["@platforms//os:linux"],
        visibility = ["//visibility:private"],
    )

    # Force oci_image and its dependency closure (base alias, layers,
    # runfiles) to be configured under linux/amd64 so the alias's
    # platform select resolves on darwin hosts. oci_push runs at the
    # host's exec config; only image construction needs the transition.
    #
    # The linux constraint here is what actually skips the whole image
    # subgraph from `bazel test //...` on darwin: target_compatible_with
    # is checked at the wrapper's parent (host) config, so on darwin the
    # wrapper is incompatible at expansion time and Bazel never enters
    # the transition that would otherwise demand a darwin->linux cross
    # CC toolchain when re-analyzing cc_binary deps. Bazel propagates
    # incompatibility through the rest of the chain (oci_push, sh_binary).
    image_linux = "_" + name + "_image_linux"
    platform_transition_filegroup(
        name = image_linux,
        srcs = [":" + image],
        target_platform = _IMAGE_TARGET_PLATFORM,
        target_compatible_with = ["@platforms//os:linux"],
        visibility = ["//visibility:private"],
    )

    # Repository and tag are passed at runtime by the wrapper script so
    # values resolve from env/.bazelrc rather than being baked into the
    # build graph.
    push = "_" + name + "_push"
    oci_push(
        name = push,
        image = ":" + image_linux,
        visibility = ["//visibility:private"],
    )

    gen = "_" + name + "_gen"
    write_file(
        name = gen,
        out = gen + ".sh",
        content = _wrapper_script_content(
            name = name,
            artifact_id = artifact_id,
            package = native.package_name(),
        ),
        is_executable = True,
    )

    sh_binary(
        name = name,
        srcs = [":" + gen],
        data = [
            ":" + push,
            "//tools/publish:docker_login_helper",
            "//tools/publish:publish_config",
        ],
        visibility = visibility,
    )
