#load("@omniglot-bazel-starter_pip_dependencies//:requirements.bzl", "requirement")
#load("@rules_mypy//mypy:mypy.bzl", "mypy_cli")

# there is an implicit dependency on mypy and 3.12 if mypy_cli is redefined
# from local rules_python requirements
#mypy_cli(
#    name = "mypy_cli",
#    mypy_requirement = requirement("mypy"),
#)
