"""Repository rule that probes the host C++ compilers (g++, clang++) for their
builtin include search directories, so the host cc toolchains adapt to whatever
gcc/clang version is installed instead of hardcoding version-specific paths.

The parsing mirrors rules_cc's unix_cc_configure.bzl (_get_cxx_include_directories):
run the compiler driver in verbose preprocess mode over an empty translation unit
and collect the directories between the "#include <...> search starts here:" and
"End of search list." markers. This is exactly the manual procedure the old
hardcoded lists were derived from (see the comment in toolchain_config.bzl).

Refresh after a host compiler upgrade with `bazel fetch --configure --force`.
"""

# Distro-specific include dirs the compiler does not report in its own search
# list but that surface (via symlink resolution) in gcc depfiles. linux-libc-dev
# keeps the arch UAPI headers here and symlinks /usr/include/x86_64-linux-gnu/asm
# to them; gcc records the resolved target, so the directory must be declared
# builtin. Harmless when absent -- a builtin dir that never matches.
EXTRA_INCLUDE_DIRS = ["/usr/lib/linux/uapi/x86"]

_START_MARKER = "#include <...> search starts here:"
_END_MARKER = "End of search list."

# Shared with remote_cc_toolchains.bzl, which probes downloaded compilers the
# same way.
def probe_include_dirs(repository_ctx, cxx_bin):
    """Returns the compiler's builtin C++ include dirs, or [] on failure."""
    result = repository_ctx.execute([str(cxx_bin), "-E", "-x", "c++", "/dev/null", "-v"])
    if result.return_code != 0:
        return []
    dirs = []
    collecting = False
    for line in result.stderr.splitlines():
        stripped = line.strip()
        if stripped == _START_MARKER:
            collecting = True
        elif stripped == _END_MARKER:
            break
        elif collecting and stripped:
            # Drop any " (framework directory)" suffix (macOS) defensively.
            dirs.append(stripped.split(" (")[0])
    return dirs

def _bin_dir(compiler_path):
    """/usr/bin/g++ -> /usr/bin/ (the prefix the other tools share)."""
    return str(compiler_path).rsplit("/", 1)[0] + "/"

def _probe_one(repository_ctx, driver_name):
    """Returns (tool_bin_dir, include_dirs) for a driver, or (None, []) if absent."""
    driver = repository_ctx.which(driver_name)
    if driver == None:
        return None, []
    include_dirs = probe_include_dirs(repository_ctx, driver)
    if not include_dirs:
        # buildifier: disable=print
        print("WARNING: could not probe builtin include dirs from {}; ".format(driver) +
              "the corresponding host toolchain will reject system headers.")
    return _bin_dir(driver), include_dirs + EXTRA_INCLUDE_DIRS

_DEFS_TEMPLATE = """\
# Generated by host_cc_discovery. Do not edit; refresh with `bazel fetch --configure --force`.
GCC_TOOL_BIN = {gcc_bin}
GCC_BUILTIN_INCLUDE_DIRECTORIES = {gcc_includes}
CLANG_TOOL_BIN = {clang_bin}
CLANG_BUILTIN_INCLUDE_DIRECTORIES = {clang_includes}
"""

def _host_cc_discovery_impl(repository_ctx):
    # Register PATH as an input so the probe re-runs when it changes
    # (which() results depend on it, e.g. after installing a compiler).
    repository_ctx.getenv("PATH")

    gcc_bin, gcc_includes = _probe_one(repository_ctx, "g++")
    clang_bin, clang_includes = _probe_one(repository_ctx, "clang++")

    if gcc_bin == None:
        # buildifier: disable=print
        print("WARNING: host g++ not found on PATH; --config=gcc_host will fail until it is installed.")
    if clang_bin == None:
        # buildifier: disable=print
        print("WARNING: host clang++ not found on PATH; --config=clang_host will fail until it is installed.")

    repository_ctx.file("BUILD.bazel", "")
    repository_ctx.file("defs.bzl", _DEFS_TEMPLATE.format(
        gcc_bin = repr(gcc_bin or "/usr/bin/"),
        gcc_includes = repr(gcc_includes),
        clang_bin = repr(clang_bin or "/usr/bin/"),
        clang_includes = repr(clang_includes),
    ))

host_cc_discovery = repository_rule(
    implementation = _host_cc_discovery_impl,
    configure = True,
    local = True,
    doc = "Probes host g++/clang++ for their builtin include dirs and tool bin dir.",
)
