"""Repository rule for remote (downloaded) C++ compilers, remote-corretto
style: a pinned vendor archive is fetched with SHA256 verification the first
time its `--config` is used, and wired through the same cc_toolchain_config as
the host compilers. Like the *_host flavours these compile and link against the
host glibc (the archives ship no libc/sysroot), so they are "pinned host
compilers", not hermetic toolchains — useful when the distro compiler is too
old or when vendor downloads must flow through an artifact proxy.

Vendors:
- gcc_remote_xpack: xPack GCC (relocatable GCC + binutils).
  https://github.com/xpack-dev-tools/gcc-xpack/releases
- clang_remote_llvm: hermeticbuild/hermetic-llvm "minimal" archive (a single
  static-musl multiplexed binary providing clang/lld/clang-tidy/clang-format
  and the llvm- binutils, ~41 MB).
  https://github.com/hermeticbuild/hermetic-llvm/releases

Fully hermetic upgrades of the same vendors exist and are the intended end
state once mature: the `llvm` BCR module (hermetic-llvm's zero-sysroot
cc_toolchain, which builds libc++/compiler-rt/libc stubs from source) is a
viable replacement for the ~50x larger toolchains_llvm distribution, pending
upstream `bazel coverage` support (hermeticbuild/hermetic-llvm#675); xPack GCC
could likewise be hardened by pairing it with a minimal downloaded sysroot.

The builtin include dirs are probed from the downloaded compiler at fetch time
(shared logic with host_cc_discovery.bzl); refresh after host header changes
with `bazel fetch --configure --force`.
"""

load(":host_cc_discovery.bzl", "EXTRA_INCLUDE_DIRS", "probe_include_dirs")

_SPECS = {
    "gcc_remote_xpack": struct(
        cxx_driver = "g++",
        # Full binutils are shipped under the same bin/, nothing to add.
        symlinks = {},
        archives = {
            "amd64": struct(
                url = "https://github.com/xpack-dev-tools/gcc-xpack/releases/download/v15.2.0-1/xpack-gcc-15.2.0-1-linux-x64.tar.gz",
                sha256 = "f6dcc3815299a23b2b4372223c4ca5f1b5a0543ed097d57eb67e0753b7c484e0",
                strip_prefix = "xpack-gcc-15.2.0-1",
            ),
            "arm64": struct(
                url = "https://github.com/xpack-dev-tools/gcc-xpack/releases/download/v15.2.0-1/xpack-gcc-15.2.0-1-linux-arm64.tar.gz",
                sha256 = "8d6e78782994ffdfdabbc8f485bc98d817d17b1f9c12e4163c7d6c50d4a16912",
                strip_prefix = "xpack-gcc-15.2.0-1",
            ),
        },
    ),
    "clang_remote_llvm": struct(
        cxx_driver = "clang++",
        # The archive only ships llvm-prefixed binutils; the toolchain config
        # tool_paths expect the classic names. ld -> ld.lld makes the clang
        # driver link with the bundled lld instead of hunting for a host ld.
        symlinks = {
            "ar": "llvm-ar",
            "dwp": "llvm-dwp",
            "ld": "ld.lld",
            "nm": "llvm-nm",
            "objcopy": "llvm-objcopy",
            "objdump": "llvm-objdump",
            "strip": "llvm-strip",
        },
        archives = {
            "amd64": struct(
                url = "https://github.com/hermeticbuild/hermetic-llvm/releases/download/llvm-22.1.8-1/llvm-toolchain-minimal-22.1.8-linux-amd64-musl.tar.zst",
                sha256 = "89f29294a584267251edac00ab723a0a74514b8e1acb7f036840d13635c66bfa",
                strip_prefix = "",
            ),
            "arm64": struct(
                url = "https://github.com/hermeticbuild/hermetic-llvm/releases/download/llvm-22.1.8-1/llvm-toolchain-minimal-22.1.8-linux-arm64-musl.tar.zst",
                sha256 = "2914968f1fff964c654627599d15ade423e17ed310b09e2d6b61e82c16a1993d",
                strip_prefix = "",
            ),
        },
    ),
}

_ARCH_TO_CPU_CONSTRAINT = {
    "amd64": "x86_64",
    "arm64": "aarch64",
}

_BUILD_TEMPLATE = """\
# Generated by remote_cc_toolchains.bzl. Do not edit.
load("@@//tools/cpp/toolchains:toolchain_config.bzl", "cc_toolchain_config")
load("@rules_cc//cc:defs.bzl", "cc_toolchain")

filegroup(name = "empty")

cc_toolchain_config(
    name = "toolchain_config",
    builtin_include_directories = {include_dirs},
    compiler_flavour_name = "{flavour}",
    tool_bin_dir = "{tool_bin_dir}",
)

cc_toolchain(
    name = "toolchain",
    all_files = ":empty",
    compiler_files = ":empty",
    dwp_files = ":empty",
    linker_files = ":empty",
    objcopy_files = ":empty",
    strip_files = ":empty",
    supports_param_files = 0,
    toolchain_config = ":toolchain_config",
    toolchain_identifier = "{flavour}_toolchain",
)

toolchain(
    name = "cc_toolchain_for_linux_{arch}",
    exec_compatible_with = [
        "@platforms//cpu:{cpu}",
        "@platforms//os:linux",
    ],
    target_compatible_with = [
        "@platforms//cpu:{cpu}",
        "@platforms//os:linux",
    ],
    toolchain = ":toolchain",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)
"""

def _normalize_arch(os_arch):
    if os_arch in ("amd64", "x86_64"):
        return "amd64"
    if os_arch in ("arm64", "aarch64"):
        return "arm64"
    return os_arch

def _remote_cc_toolchain_impl(ctx):
    spec = _SPECS[ctx.attr.flavour]
    if ctx.os.name != "linux":
        fail("remote cc toolchain {} supports Linux only (host os: {}).".format(
            ctx.attr.flavour,
            ctx.os.name,
        ))
    arch = _normalize_arch(ctx.os.arch)
    if arch not in spec.archives:
        fail("remote cc toolchain {} has no archive for host arch {}.".format(
            ctx.attr.flavour,
            arch,
        ))
    archive = spec.archives[arch]

    ctx.download_and_extract(
        url = archive.url,
        sha256 = archive.sha256,
        stripPrefix = archive.strip_prefix,
        output = "dist",
    )
    for link_name, target in spec.symlinks.items():
        ctx.symlink("dist/bin/" + target, "dist/bin/" + link_name)

    cxx = ctx.path("dist/bin/" + spec.cxx_driver)
    include_dirs = probe_include_dirs(ctx, cxx)
    if not include_dirs:
        fail("could not probe builtin include dirs from downloaded {} — the host ".format(cxx) +
             "may be missing the libc headers the compiler links against.")

    # The probed dirs mix repo-internal paths (the compiler's own headers) with
    # host paths (/usr/include). Also declare the realpath of each, so include
    # validation still passes if Bazel serves the repo through a symlink (repo
    # contents cache) and the compiler reports resolved paths in depfiles.
    dirs = []
    for d in include_dirs:
        for variant in (d, str(ctx.path(d).realpath)):
            if variant not in dirs:
                dirs.append(variant)
    dirs += EXTRA_INCLUDE_DIRS

    ctx.file("BUILD.bazel", _BUILD_TEMPLATE.format(
        arch = arch,
        cpu = _ARCH_TO_CPU_CONSTRAINT[arch],
        flavour = ctx.attr.flavour,
        include_dirs = repr(dirs),
        tool_bin_dir = str(ctx.path("dist/bin")) + "/",
    ))

remote_cc_toolchain = repository_rule(
    implementation = _remote_cc_toolchain_impl,
    attrs = {
        "flavour": attr.string(
            mandatory = True,
            values = list(_SPECS.keys()),
            doc = "Which pinned compiler to download and wire up.",
        ),
    },
    configure = True,
    doc = "Downloads a pinned vendor C++ compiler and wires it as a host-linked cc toolchain.",
)
